In [2]:
faqs="""Saandhil Agarwal
 Bachelor of Technology
 Information Technology
 Birla Institute of Technology, Mesra
 
Education
 Birla Institute of Technology, Mesra
 B.Tech in Information Technology
 New Look Uchtar Madhyamik Vidyalaya, Kota
 Central Board of Secondary Education
 
Experience
 YHills
 Campus Ambassador
 Organized and managed with a group of students for the smooth enrollment of students in courses
 Addressed queries,implemented innovative strategies and increased student engagement significantly
 
Personal Projects
 AI Powered Movie Recommender System (Machine Learning)
 Applied comprehensive feature engineering techniques including feature transformation, feature extraction and One Hot
 Encoding along with pandas profiling for thorough data analysis. Utilized text vectorization, cosine similarities and
 integrated APIs with streamlit’s interactive widgets with effortless deployment for movie recommendation
Beverage Vista- A sales dashboard of refreshment drinks (Power BI)
 Leveraged Power BI for detailed analytics in American beverage sales along with dynamic charts using filters & slices.
 Explored trends across states and cities and implemented tool tips for insights contributing to strategic decision-making
 Next Word Predictor using LSTM and LLMs (Deep Learning, NLP)
 Developed a Natural Language Processing Model using LSTM & LLM techniques for predicting the next word in text se
quences using language modelling. Used Keras, PyTorch and TensorFlow frameworks to implement the model incorporating
 embedding layers, LSTM and Softmax layers to achieve high accuracy through hyper-parameter tuning.


Technical Skills and Interests
 Languages and Libraries: Python, C/C++, Numpy, Pandas, Matplotlib, Scikit-learn, Seaborn, Streamlit, SQL
 Developer Tools: Git/GitHub, Pycharm, Power BI, Jupyter Notebook, Google Colab, VS-Code
 Frameworks: Keras, TensorFlow, PyTorch
 Interests: Machine Learning, Deep Learning, NLP, GenAI
 Coursework:– Image Processing and Pattern Recognition– Natural Language Processing– Data Mining– Operating Systems and Data Base Management Systems
 
 Positions of Responsibility
 Event Organizer, Sports and Adventure Club, BIT Mesra
 Senior Executive, Dhwani, BIT Mesra
 
 Certifications and Achievements
 Google Analytics Accreditation
 Showcasing proficiency in data analysis and visualization for informed decision making
Udemy’s Machine Learning Course
 Accomplished a comprehensive "Machine Learning in 21 days" course on Udemy applying algorithms on real world datasets
 Special Mention in Model United Nations
 Recieved a Special Mention and a Verbal Mention in the UNHRC Committee for 2 consecutive years"""

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

C:\Users\saandhil agarwal\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
tokenizer=Tokenizer()

In [5]:
tokenizer.fit_on_texts([faqs])

In [6]:
tokenizer.word_index

{'and': 1,
 'of': 2,
 'in': 3,
 'for': 4,
 'a': 5,
 'learning': 6,
 'technology': 7,
 'with': 8,
 'mesra': 9,
 'the': 10,
 'machine': 11,
 'data': 12,
 'using': 13,
 'feature': 14,
 'power': 15,
 'bi': 16,
 'to': 17,
 'lstm': 18,
 'language': 19,
 'model': 20,
 'mention': 21,
 'information': 22,
 'birla': 23,
 'institute': 24,
 'education': 25,
 'students': 26,
 'implemented': 27,
 'movie': 28,
 'comprehensive': 29,
 'techniques': 30,
 'along': 31,
 'pandas': 32,
 'analysis': 33,
 'text': 34,
 'beverage': 35,
 'sales': 36,
 'analytics': 37,
 'decision': 38,
 'making': 39,
 'next': 40,
 'word': 41,
 'deep': 42,
 'nlp': 43,
 'natural': 44,
 'processing': 45,
 'keras': 46,
 'pytorch': 47,
 'tensorflow': 48,
 'frameworks': 49,
 'layers': 50,
 'interests': 51,
 'c': 52,
 'google': 53,
 'systems': 54,
 'bit': 55,
 'course': 56,
 'on': 57,
 'special': 58,
 'saandhil': 59,
 'agarwal': 60,
 'bachelor': 61,
 'b': 62,
 'tech': 63,
 'new': 64,
 'look': 65,
 'uchtar': 66,
 'madhyamik': 67,
 'vidyal

In [7]:
len(tokenizer.word_index)

228

In [8]:
for sentence in faqs.split('\n'):
    print(sentence)

Saandhil Agarwal
 Bachelor of Technology
 Information Technology
 Birla Institute of Technology, Mesra
 
Education
 Birla Institute of Technology, Mesra
 B.Tech in Information Technology
 New Look Uchtar Madhyamik Vidyalaya, Kota
 Central Board of Secondary Education
 
Experience
 YHills
 Campus Ambassador
 Organized and managed with a group of students for the smooth enrollment of students in courses
 Addressed queries,implemented innovative strategies and increased student engagement significantly
 
Personal Projects
 AI Powered Movie Recommender System (Machine Learning)
 Applied comprehensive feature engineering techniques including feature transformation, feature extraction and One Hot
 Encoding along with pandas profiling for thorough data analysis. Utilized text vectorization, cosine similarities and
 integrated APIs with streamlit’s interactive widgets with effortless deployment for movie recommendation
Beverage Vista- A sales dashboard of refreshment drinks (Power BI)
 Leverag

In [9]:
for sentence in faqs.split('\n'):
    print(tokenizer.texts_to_sequences([sentence])[0])

[59, 60]
[61, 2, 7]
[22, 7]
[23, 24, 2, 7, 9]
[]
[25]
[23, 24, 2, 7, 9]
[62, 63, 3, 22, 7]
[64, 65, 66, 67, 68, 69]
[70, 71, 2, 72, 25]
[]
[73]
[74]
[75, 76]
[77, 1, 78, 8, 5, 79, 2, 26, 4, 10, 80, 81, 2, 26, 3, 82]
[83, 84, 27, 85, 86, 1, 87, 88, 89, 90]
[]
[91, 92]
[93, 94, 28, 95, 96, 11, 6]
[97, 29, 14, 98, 30, 99, 14, 100, 14, 101, 1, 102, 103]
[104, 31, 8, 32, 105, 4, 106, 12, 33, 107, 34, 108, 109, 110, 1]
[111, 112, 8, 113, 114, 115, 8, 116, 117, 4, 28, 118]
[35, 119, 5, 36, 120, 2, 121, 122, 15, 16]
[123, 15, 16, 4, 124, 37, 3, 125, 35, 36, 31, 8, 126, 127, 13, 128, 129]
[130, 131, 132, 133, 1, 134, 1, 27, 135, 136, 4, 137, 138, 17, 139, 38, 39]
[40, 41, 140, 13, 18, 1, 141, 42, 6, 43]
[142, 5, 44, 19, 45, 20, 13, 18, 143, 30, 4, 144, 10, 40, 41, 3, 34, 145]
[146, 13, 19, 147, 148, 46, 47, 1, 48, 49, 17, 149, 10, 20, 150]
[151, 50, 18, 1, 152, 50, 17, 153, 154, 155, 156, 157, 158, 159]
[]
[]
[160, 161, 1, 51]
[162, 1, 163, 164, 52, 52, 165, 32, 166, 167, 168, 169, 170, 171]
[1

In [10]:
input_sequences = []
for sentence in faqs.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])


In [11]:
input_sequences

[[59, 60],
 [61, 2],
 [61, 2, 7],
 [22, 7],
 [23, 24],
 [23, 24, 2],
 [23, 24, 2, 7],
 [23, 24, 2, 7, 9],
 [23, 24],
 [23, 24, 2],
 [23, 24, 2, 7],
 [23, 24, 2, 7, 9],
 [62, 63],
 [62, 63, 3],
 [62, 63, 3, 22],
 [62, 63, 3, 22, 7],
 [64, 65],
 [64, 65, 66],
 [64, 65, 66, 67],
 [64, 65, 66, 67, 68],
 [64, 65, 66, 67, 68, 69],
 [70, 71],
 [70, 71, 2],
 [70, 71, 2, 72],
 [70, 71, 2, 72, 25],
 [75, 76],
 [77, 1],
 [77, 1, 78],
 [77, 1, 78, 8],
 [77, 1, 78, 8, 5],
 [77, 1, 78, 8, 5, 79],
 [77, 1, 78, 8, 5, 79, 2],
 [77, 1, 78, 8, 5, 79, 2, 26],
 [77, 1, 78, 8, 5, 79, 2, 26, 4],
 [77, 1, 78, 8, 5, 79, 2, 26, 4, 10],
 [77, 1, 78, 8, 5, 79, 2, 26, 4, 10, 80],
 [77, 1, 78, 8, 5, 79, 2, 26, 4, 10, 80, 81],
 [77, 1, 78, 8, 5, 79, 2, 26, 4, 10, 80, 81, 2],
 [77, 1, 78, 8, 5, 79, 2, 26, 4, 10, 80, 81, 2, 26],
 [77, 1, 78, 8, 5, 79, 2, 26, 4, 10, 80, 81, 2, 26, 3],
 [77, 1, 78, 8, 5, 79, 2, 26, 4, 10, 80, 81, 2, 26, 3, 82],
 [83, 84],
 [83, 84, 27],
 [83, 84, 27, 85],
 [83, 84, 27, 85, 86],
 [83, 84

In [12]:
max_len=max([len(x) for x in input_sequences])

In [13]:
max([len(x) for x in input_sequences])

19

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences, maxlen =max_len, padding='pre')

In [15]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  59,  60],
       [  0,   0,   0, ...,   0,  61,   2],
       [  0,   0,   0, ...,  61,   2,   7],
       ...,
       [  0,   0,   0, ..., 225,   4, 226],
       [  0,   0,   0, ...,   4, 226, 227],
       [  0,   0,   0, ..., 226, 227, 228]])

In [16]:
X=padded_input_sequences[:,:-1]

In [17]:
y=padded_input_sequences[:,-1]

In [18]:
X.shape

(309, 18)

In [19]:
y.shape

(309,)

In [20]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=229)

In [21]:
y.shape

(309, 229)

In [22]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Embedding, LSTM, Dense


In [23]:
model=Sequential()
model.add(Embedding(229,100,input_length=18))
model.add(LSTM(150))
model.add(Dense(229,activation='softmax'))

In [24]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 18, 100)           22900     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 229)               34579     
                                                                 
Total params: 208079 (812.81 KB)
Trainable params: 208079 (812.81 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
X

array([[  0,   0,   0, ...,   0,   0,  59],
       [  0,   0,   0, ...,   0,   0,  61],
       [  0,   0,   0, ...,   0,  61,   2],
       ...,
       [  0,   0,   0, ..., 224, 225,   4],
       [  0,   0,   0, ..., 225,   4, 226],
       [  0,   0,   0, ...,   4, 226, 227]])

In [27]:
model.fit(X,y,epochs=100)

Epoch 1/100
10/10 [==============================] - 2s 12ms/step - loss: 5.4304 - accuracy: 0.0162
Epoch 2/100
10/10 [==============================] - 0s 10ms/step - loss: 5.3224 - accuracy: 0.0550
Epoch 3/100
10/10 [==============================] - 0s 10ms/step - loss: 5.1689 - accuracy: 0.0550
Epoch 4/100
10/10 [==============================] - 0s 10ms/step - loss: 5.0774 - accuracy: 0.0550
Epoch 5/100
10/10 [==============================] - 0s 10ms/step - loss: 5.0220 - accuracy: 0.0550
Epoch 6/100
10/10 [==============================] - 0s 10ms/step - loss: 4.9624 - accuracy: 0.0550
Epoch 7/100
10/10 [==============================] - 0s 10ms/step - loss: 4.8956 - accuracy: 0.0550
Epoch 8/100
10/10 [==============================] - 0s 10ms/step - loss: 4.8288 - accuracy: 0.0485
Epoch 9/100
10/10 [==============================] - 0s 11ms/step - loss: 4.7336 - accuracy: 0.0615
Epoch 10/100
10/10 [==============================] - 0s 9ms/step - loss: 4.6557 - accuracy: 0.0647


10/10 [==============================] - 0s 16ms/step - loss: 0.2941 - accuracy: 1.0000
Epoch 83/100
10/10 [==============================] - 0s 15ms/step - loss: 0.2838 - accuracy: 1.0000
Epoch 84/100
10/10 [==============================] - 0s 15ms/step - loss: 0.2731 - accuracy: 1.0000
Epoch 85/100
10/10 [==============================] - 0s 16ms/step - loss: 0.2639 - accuracy: 1.0000
Epoch 86/100
10/10 [==============================] - 0s 17ms/step - loss: 0.2537 - accuracy: 1.0000
Epoch 87/100
10/10 [==============================] - 0s 16ms/step - loss: 0.2456 - accuracy: 1.0000
Epoch 88/100
10/10 [==============================] - 0s 16ms/step - loss: 0.2384 - accuracy: 1.0000
Epoch 89/100
10/10 [==============================] - 0s 15ms/step - loss: 0.2297 - accuracy: 1.0000
Epoch 90/100
10/10 [==============================] - 0s 15ms/step - loss: 0.2225 - accuracy: 1.0000
Epoch 91/100
10/10 [==============================] - 0s 15ms/step - loss: 0.2138 - accuracy: 1.0000
Epo

In [28]:
text = "Birla"
#tokenize
token_text=tokenizer.texts_to_sequences([text])[0]



In [29]:
#padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_text=pad_sequences([token_text],maxlen=18,padding='pre')
print(padded_input_text)




[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 23]]


In [30]:
#predict
model.predict(padded_input_text)

1/1 [==============================] - 0s 363ms/step


array([[6.12876818e-07, 6.46784320e-04, 1.77913792e-02, 3.16574215e-03,
        1.93364085e-05, 1.93819273e-04, 5.13899176e-05, 2.18510279e-03,
        4.36847995e-06, 3.12293385e-04, 3.96327141e-06, 1.42812409e-04,
        2.01001640e-05, 3.47979862e-04, 1.39749711e-04, 6.59561977e-07,
        2.69195738e-07, 1.85360693e-06, 2.30563478e-06, 5.26767217e-05,
        2.50080921e-05, 3.70261201e-04, 7.50894151e-06, 2.44908279e-07,
        9.28039670e-01, 8.33465219e-06, 1.98169819e-05, 1.71096599e-06,
        7.17878575e-05, 2.79009255e-04, 1.17314348e-05, 3.51149683e-05,
        1.06636537e-06, 6.87312740e-06, 5.96481777e-06, 1.21210246e-06,
        1.98355301e-05, 1.04548679e-04, 7.85068369e-06, 4.12458257e-06,
        5.55063525e-06, 8.78723513e-04, 4.32483876e-06, 1.76996593e-06,
        3.20852851e-04, 1.33884279e-03, 4.24756618e-05, 3.31203387e-06,
        1.69063533e-05, 3.11834310e-06, 2.25201006e-06, 3.31890333e-05,
        2.60028976e-08, 1.34672263e-07, 4.27097302e-06, 1.119721

In [31]:
model.predict(padded_input_text).shape

1/1 [==============================] - 0s 21ms/step


(1, 229)

In [32]:
import numpy as np
np.argmax(model.predict(padded_input_text))

1/1 [==============================] - 0s 22ms/step


24

In [33]:
tokenizer.word_index

{'and': 1,
 'of': 2,
 'in': 3,
 'for': 4,
 'a': 5,
 'learning': 6,
 'technology': 7,
 'with': 8,
 'mesra': 9,
 'the': 10,
 'machine': 11,
 'data': 12,
 'using': 13,
 'feature': 14,
 'power': 15,
 'bi': 16,
 'to': 17,
 'lstm': 18,
 'language': 19,
 'model': 20,
 'mention': 21,
 'information': 22,
 'birla': 23,
 'institute': 24,
 'education': 25,
 'students': 26,
 'implemented': 27,
 'movie': 28,
 'comprehensive': 29,
 'techniques': 30,
 'along': 31,
 'pandas': 32,
 'analysis': 33,
 'text': 34,
 'beverage': 35,
 'sales': 36,
 'analytics': 37,
 'decision': 38,
 'making': 39,
 'next': 40,
 'word': 41,
 'deep': 42,
 'nlp': 43,
 'natural': 44,
 'processing': 45,
 'keras': 46,
 'pytorch': 47,
 'tensorflow': 48,
 'frameworks': 49,
 'layers': 50,
 'interests': 51,
 'c': 52,
 'google': 53,
 'systems': 54,
 'bit': 55,
 'course': 56,
 'on': 57,
 'special': 58,
 'saandhil': 59,
 'agarwal': 60,
 'bachelor': 61,
 'b': 62,
 'tech': 63,
 'new': 64,
 'look': 65,
 'uchtar': 66,
 'madhyamik': 67,
 'vidyal

In [34]:
pos=np.argmax(model.predict(padded_input_text))
for word,index in tokenizer.word_index.items():
  if index==pos:
    print(word)

1/1 [==============================] - 0s 19ms/step
institute


In [35]:
import time
text="frameworks"
 
for i in range(5):
    #tokenize
    token_text=tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_input_text=pad_sequences([token_text],maxlen=18,padding='pre')
    #predict
    pos=np.argmax(model.predict(padded_input_text))
    
    for word,index in tokenizer.word_index.items():
        if index ==pos:
            text=text+ " " +word
            print(text)
            time.sleep(2)

    

1/1 [==============================] - 0s 20ms/step
frameworks keras
1/1 [==============================] - 0s 22ms/step
frameworks keras tensorflow
1/1 [==============================] - 0s 14ms/step
frameworks keras tensorflow pytorch
1/1 [==============================] - 0s 13ms/step
frameworks keras tensorflow pytorch and
1/1 [==============================] - 0s 17ms/step
frameworks keras tensorflow pytorch and tensorflow
